#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaStandaloneTimer

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaStandaloneTimer.AthenaStandaloneTimer_C
// 0x0000 (0x0250 - 0x0250)
class UAthenaStandaloneTimer_C final : public UAthenaTimeWidgetBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaStandaloneTimer_C">();
	}
	static class UAthenaStandaloneTimer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaStandaloneTimer_C>();
	}
};

}

