#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaSpectatorPlayerStatus

#include "Basic.hpp"

#include "AthenaSpectatorPlayerStatus_classes.hpp"
#include "AthenaSpectatorPlayerStatus_parameters.hpp"


namespace SDK
{

// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.ExecuteUbergraph_AthenaSpectatorPlayerStatus
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpectatorPlayerStatus_C::ExecuteUbergraph_AthenaSpectatorPlayerStatus(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "ExecuteUbergraph_AthenaSpectatorPlayerStatus");

	Params::AthenaSpectatorPlayerStatus_C_ExecuteUbergraph_AthenaSpectatorPlayerStatus Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.FollowedPlayerChanged
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerState*                 NewFollowedPlayer                                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpectatorPlayerStatus_C::FollowedPlayerChanged(const class AFortPlayerState* NewFollowedPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "FollowedPlayerChanged");

	Params::AthenaSpectatorPlayerStatus_C_FollowedPlayerChanged Parms{};

	Parms.NewFollowedPlayer = NewFollowedPlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.UpdatePlayerTeam
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeamNumber                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     TeamColor                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpectatorPlayerStatus_C::UpdatePlayerTeam(const int32 TeamNumber, const struct FLinearColor& TeamColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "UpdatePlayerTeam");

	Params::AthenaSpectatorPlayerStatus_C_UpdatePlayerTeam Parms{};

	Parms.TeamNumber = TeamNumber;
	Parms.TeamColor = std::move(TeamColor);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.UpdatePlayerLocationText
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Param_PlayerNameText                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UAthenaSpectatorPlayerStatus_C::UpdatePlayerLocationText(const class FText& Param_PlayerNameText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "UpdatePlayerLocationText");

	Params::AthenaSpectatorPlayerStatus_C_UpdatePlayerLocationText Parms{};

	Parms.Param_PlayerNameText = std::move(Param_PlayerNameText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.UpdatePlayerNameText
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Param_PlayerNameText                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UAthenaSpectatorPlayerStatus_C::UpdatePlayerNameText(const class FText& Param_PlayerNameText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "UpdatePlayerNameText");

	Params::AthenaSpectatorPlayerStatus_C_UpdatePlayerNameText Parms{};

	Parms.Param_PlayerNameText = std::move(Param_PlayerNameText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UAthenaSpectatorPlayerStatus_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaSpectatorPlayerStatus.AthenaSpectatorPlayerStatus_C.SetLocationVisibility
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Param_IsVisible                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UAthenaSpectatorPlayerStatus_C::SetLocationVisibility(bool Param_IsVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpectatorPlayerStatus_C", "SetLocationVisibility");

	Params::AthenaSpectatorPlayerStatus_C_SetLocationVisibility Parms{};

	Parms.Param_IsVisible = Param_IsVisible;

	UObject::ProcessEvent(Func, &Parms);
}

}

