#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaEventMatchPlayerGridTeamWidget

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaEventMatchPlayerGridTeamWidget.AthenaEventMatchPlayerGridTeamWidget_C
// 0x0018 (0x0280 - 0x0268)
class UAthenaEventMatchPlayerGridTeamWidget_C final : public UAthenaEventMatchTeamWidgetBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0268(0x0008)(Transient, DuplicateTransient)
	class UUniformGridPanel*                      PlayerGrid;                                        // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          TeamColorBorder;                                   // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_AthenaEventMatchPlayerGridTeamWidget(int32 EntryPoint);
	void OnPlayerWidgetAdded(class UAthenaEventMatchPlayerWidgetBase* PlayerWidget);
	void AddToGrid(class UAthenaEventMatchPlayerWidgetBase* PlayerWidget);
	void OnGridSizeChanged(int32 InGridSize);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaEventMatchPlayerGridTeamWidget_C">();
	}
	static class UAthenaEventMatchPlayerGridTeamWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaEventMatchPlayerGridTeamWidget_C>();
	}
};

}

