#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_MissileBattery_Homing_Placement

#include "Basic.hpp"


namespace SDK::Params
{

// Function B_MissileBattery_Homing_Placement.B_MissileBattery_Homing_Placement_C.ExecuteUbergraph_B_MissileBattery_Homing_Placement
// 0x0004 (0x0004 - 0x0000)
struct B_MissileBattery_Homing_Placement_C_ExecuteUbergraph_B_MissileBattery_Homing_Placement final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

