#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Placement_Pack_MissileBattery

#include "Basic.hpp"


namespace SDK::Params
{

// Function B_Placement_Pack_MissileBattery.B_Placement_Pack_MissileBattery_C.ExecuteUbergraph_B_Placement_Pack_MissileBattery
// 0x0004 (0x0004 - 0x0000)
struct B_Placement_Pack_MissileBattery_C_ExecuteUbergraph_B_Placement_Pack_MissileBattery final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

