#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BorderMinusCompareHeader

#include "Basic.hpp"

#include "BorderMinusShellTopBar_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border-CompareHeader.Border-CompareHeader_C
// 0x0000 (0x00B0 - 0x00B0)
class UBorderMinusCompareHeader_C final : public UBorderMinusShellTopBar_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border-CompareHeader_C">();
	}
	static class UBorderMinusCompareHeader_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorderMinusCompareHeader_C>();
	}
};

}

