#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BorderMinusTabMMinusSolidMinus30pc

#include "Basic.hpp"

#include "BorderMinusTabMMinusSolid_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border-TabM-Solid-30pc.Border-TabM-Solid-30pc_C
// 0x0000 (0x00B0 - 0x00B0)
class UBorderMinusTabMMinusSolidMinus30pc_C final : public UBorderMinusTabMMinusSolid_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border-TabM-Solid-30pc_C">();
	}
	static class UBorderMinusTabMMinusSolidMinus30pc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorderMinusTabMMinusSolidMinus30pc_C>();
	}
};

}

