#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FortExpeditionVehicleTileItemWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_FortExpeditionVehicleTileItemWidget.BP_FortExpeditionVehicleTileItemWidget_C
// 0x0038 (0x08D8 - 0x08A0)
class UBP_FortExpeditionVehicleTileItemWidget_C final : public UFortExpeditionVehicleTileItemWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08A0(0x0008)(Transient, DuplicateTransient)
	class UBasicRatingWidget_C*                   BasicRatingWidget;                                 // 0x08A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Name_BP_FortExpeditionVehicleTileItemWidget_C;     // 0x08B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 VehicleIcon;                                       // 0x08B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FName                                   SquadIdName;                                       // 0x08C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	UMulticastDelegateProperty_                   OnVehicleSelected;                                 // 0x08C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void OnVehicleSelected__DelegateSignature(class FName Param_SquadId);
	void ExecuteUbergraph_BP_FortExpeditionVehicleTileItemWidget(int32 EntryPoint);
	void BP_OnClicked();
	void OnListItemObjectSet(class UObject* ListItemObject);
	void Set_Icon(const class FName& Param_SquadId);
	void Set_Rating(const class FName& Param_SquadId);
	void Set_Name(const class FName Param_SquadId);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FortExpeditionVehicleTileItemWidget_C">();
	}
	static class UBP_FortExpeditionVehicleTileItemWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_FortExpeditionVehicleTileItemWidget_C>();
	}
};

}

