#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusSolidMinusSquareMMinusSelectable

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Solid-SquareM-Selectable.ButtonStyle-Solid-SquareM-Selectable_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonStyleMinusSolidMinusSquareMMinusSelectable_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Solid-SquareM-Selectable_C">();
	}
	static class UButtonStyleMinusSolidMinusSquareMMinusSelectable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusSolidMinusSquareMMinusSelectable_C>();
	}
};

}

