#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusSlotMinusPeopleM

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Slot-PeopleM.ButtonStyle-Slot-PeopleM_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonStyleMinusSlotMinusPeopleM_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Slot-PeopleM_C">();
	}
	static class UButtonStyleMinusSlotMinusPeopleM_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusSlotMinusPeopleM_C>();
	}
};

}

