#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusPrimaryMinusL

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Primary-L.ButtonStyle-Primary-L_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonStyleMinusPrimaryMinusL_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Primary-L_C">();
	}
	static class UButtonStyleMinusPrimaryMinusL_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusPrimaryMinusL_C>();
	}
};

}

