#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusOutlineMinusFadedWhite

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Outline-FadedWhite.ButtonStyle-Outline-FadedWhite_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonStyleMinusOutlineMinusFadedWhite_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Outline-FadedWhite_C">();
	}
	static class UButtonStyleMinusOutlineMinusFadedWhite_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusOutlineMinusFadedWhite_C>();
	}
};

}

