#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusSolidMinusSquareMinusCollectionBook

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Solid-Square-CollectionBook.ButtonStyle-Solid-Square-CollectionBook_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonStyleMinusSolidMinusSquareMinusCollectionBook_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Solid-Square-CollectionBook_C">();
	}
	static class UButtonStyleMinusSolidMinusSquareMinusCollectionBook_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusSolidMinusSquareMinusCollectionBook_C>();
	}
};

}

