#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusSlotMinusPeopleLMinusXL

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Slot-PeopleL-XL.ButtonStyle-Slot-PeopleL-XL_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonStyleMinusSlotMinusPeopleLMinusXL_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Slot-PeopleL-XL_C">();
	}
	static class UButtonStyleMinusSlotMinusPeopleLMinusXL_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusSlotMinusPeopleLMinusXL_C>();
	}
};

}

