#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusTransparentWithCuesMinusXSMinusB_OverlayYellow

#include "Basic.hpp"

#include "ButtonStyleMinusMediumTransparentNoCues_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-TransparentWithCues-XS-B_OverlayYellow.ButtonStyle-TransparentWithCues-XS-B_OverlayYellow_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonStyleMinusTransparentWithCuesMinusXSMinusB_OverlayYellow_C final : public UButtonStyleMinusMediumTransparentNoCues_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-TransparentWithCues-XS-B_OverlayYellow_C">();
	}
	static class UButtonStyleMinusTransparentWithCuesMinusXSMinusB_OverlayYellow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusTransparentWithCuesMinusXSMinusB_OverlayYellow_C>();
	}
};

}

