#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonMinusSkillTreeMinusMMinusPeople

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Button-SkillTree-M-People.Button-SkillTree-M-People_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonMinusSkillTreeMinusMMinusPeople_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Button-SkillTree-M-People_C">();
	}
	static class UButtonMinusSkillTreeMinusMMinusPeople_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonMinusSkillTreeMinusMMinusPeople_C>();
	}
};

}

