#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonMinusSkillTreeMinusNone

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Button-SkillTree-None.Button-SkillTree-None_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonMinusSkillTreeMinusNone_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Button-SkillTree-None_C">();
	}
	static class UButtonMinusSkillTreeMinusNone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonMinusSkillTreeMinusNone_C>();
	}
};

}

