#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusOutlineEmptyFill

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-OutlineEmptyFill.ButtonStyle-OutlineEmptyFill_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonStyleMinusOutlineEmptyFill_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-OutlineEmptyFill_C">();
	}
	static class UButtonStyleMinusOutlineEmptyFill_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusOutlineEmptyFill_C>();
	}
};

}

