#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusOutlineMinusXPBar

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Outline-XPBar.ButtonStyle-Outline-XPBar_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonStyleMinusOutlineMinusXPBar_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Outline-XPBar_C">();
	}
	static class UButtonStyleMinusOutlineMinusXPBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusOutlineMinusXPBar_C>();
	}
};

}

