#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonMinusSkillTreeMinusL

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Button-SkillTree-L.Button-SkillTree-L_C
// 0x0000 (0x04F0 - 0x04F0)
class UButtonMinusSkillTreeMinusL_C : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Button-SkillTree-L_C">();
	}
	static class UButtonMinusSkillTreeMinusL_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonMinusSkillTreeMinusL_C>();
	}
};

}

