#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CollectionBookPurchasePanel

#include "Basic.hpp"

#include "CollectionBookPurchasePanel_classes.hpp"
#include "CollectionBookPurchasePanel_parameters.hpp"


namespace SDK
{

// Function CollectionBookPurchasePanel.CollectionBookPurchasePanel_C.ExecuteUbergraph_CollectionBookPurchasePanel
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCollectionBookPurchasePanel_C::ExecuteUbergraph_CollectionBookPurchasePanel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CollectionBookPurchasePanel_C", "ExecuteUbergraph_CollectionBookPurchasePanel");

	Params::CollectionBookPurchasePanel_C_ExecuteUbergraph_CollectionBookPurchasePanel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CollectionBookPurchasePanel.CollectionBookPurchasePanel_C.BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCollectionBookPurchasePanel_C::BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CollectionBookPurchasePanel_C", "BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature");

	Params::CollectionBookPurchasePanel_C_BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CollectionBookPurchasePanel.CollectionBookPurchasePanel_C.SetItem
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortItem*                        Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FFortCollectionBookSlotData      SlotData                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UCollectionBookPurchasePanel_C::SetItem(class UFortItem* Item, const struct FFortCollectionBookSlotData& SlotData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CollectionBookPurchasePanel_C", "SetItem");

	Params::CollectionBookPurchasePanel_C_SetItem Parms{};

	Parms.Item = Item;
	Parms.SlotData = std::move(SlotData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function CollectionBookPurchasePanel.CollectionBookPurchasePanel_C.SetOwningPurchaseWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCollectionBookPurchaseWidget_C*  Param_OwningPurchaseWidget                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCollectionBookPurchasePanel_C::SetOwningPurchaseWidget(class UCollectionBookPurchaseWidget_C* Param_OwningPurchaseWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CollectionBookPurchasePanel_C", "SetOwningPurchaseWidget");

	Params::CollectionBookPurchasePanel_C_SetOwningPurchaseWidget Parms{};

	Parms.Param_OwningPurchaseWidget = Param_OwningPurchaseWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CollectionBookPurchasePanel.CollectionBookPurchasePanel_C.PopulateCosts
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Param_bHasRequiredResources                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UCollectionBookPurchasePanel_C::PopulateCosts(bool* Param_bHasRequiredResources)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CollectionBookPurchasePanel_C", "PopulateCosts");

	Params::CollectionBookPurchasePanel_C_PopulateCosts Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_bHasRequiredResources != nullptr)
		*Param_bHasRequiredResources = Parms.Param_bHasRequiredResources;
}


// Function CollectionBookPurchasePanel.CollectionBookPurchasePanel_C.PopulateError
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UCollectionBookPurchasePanel_C::PopulateError()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CollectionBookPurchasePanel_C", "PopulateError");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CollectionBookPurchasePanel.CollectionBookPurchasePanel_C.CenterButtonHack
// (Public, BlueprintCallable, BlueprintEvent)

void UCollectionBookPurchasePanel_C::CenterButtonHack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CollectionBookPurchasePanel_C", "CenterButtonHack");

	UObject::ProcessEvent(Func, nullptr);
}

}

