#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DA_GuidedMissilePack

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DA_GuidedMissilePack.DA_GuidedMissilePack_C
// 0x0008 (0x0BB8 - 0x0BB0)
class ADA_GuidedMissilePack_C final : public AFortCustomizableAbilityDecoTool
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BB0(0x0008)(Transient, DuplicateTransient)

public:
	void BPPressTrigger(class AFortDecoHelper* FortDecoHelper);
	void ExecuteUbergraph_DA_GuidedMissilePack(int32 EntryPoint);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DA_GuidedMissilePack_C">();
	}
	static class ADA_GuidedMissilePack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADA_GuidedMissilePack_C>();
	}
};

}

