#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortReplayNotification

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FortReplayNotification.FortReplayNotification_C
// 0x0090 (0x02A0 - 0x0210)
class UFortReplayNotification_C final : public UCommonUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0210(0x0008)(Transient, DuplicateTransient)
	class UCommonBorder*                          Border;                                            // 0x0218(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Notification;                                      // 0x0220(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         TimeToDisplay;                                     // 0x0228(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FadeInterpSpeed;                                   // 0x022C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsFading;                                          // 0x0230(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_56FA[0x3];                                     // 0x0231(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         RemainingTime;                                     // 0x0234(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   FullyVisible;                                      // 0x0238(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   FullyHidden;                                       // 0x0250(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   GameOnly;                                          // 0x0268(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   ReplayOnly;                                        // 0x0280(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	ESlateVisibility                              PendingVisibility;                                 // 0x0298(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_FortReplayNotification(int32 EntryPoint);
	void Construct();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void ShowNotification(const class FText& NotificationText);
	void TickFade(float DeltaTime);
	void StartFading();
	void TickRemainingTime(float DeltaTime);
	void SetNotificationVisibility(ESlateVisibility Param_Visibility);
	void IsVisibilityNotification(const class FText& Param_Notification, bool* Param_IsVisibilityNotification);
	void GetVisibilityText(EHudVisibilityState Param_Visibility, class FText* Text);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FortReplayNotification_C">();
	}
	static class UFortReplayNotification_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortReplayNotification_C>();
	}
};

}

