#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_ImpactImmunity_TagTriggered

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_ImpactImmunity_TagTriggered.GE_ImpactImmunity_TagTriggered_C
// 0x0000 (0x0638 - 0x0638)
class UGE_ImpactImmunity_TagTriggered_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_ImpactImmunity_TagTriggered_C">();
	}
	static class UGE_ImpactImmunity_TagTriggered_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_ImpactImmunity_TagTriggered_C>();
	}
};

}

