#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_MilitaryLauncher_AoEDamage_Athena

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_MilitaryLauncher_AoEDamage_Athena.GE_MilitaryLauncher_AoEDamage_Athena_C
// 0x0000 (0x0638 - 0x0638)
class UGE_MilitaryLauncher_AoEDamage_Athena_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_MilitaryLauncher_AoEDamage_Athena_C">();
	}
	static class UGE_MilitaryLauncher_AoEDamage_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_MilitaryLauncher_AoEDamage_Athena_C>();
	}
};

}

