#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Jim_Land_CamShake

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Jim_Land_CamShake.Jim_Land_CamShake_C
// 0x0000 (0x0160 - 0x0160)
class UJim_Land_CamShake_C final : public UCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Jim_Land_CamShake_C">();
	}
	static class UJim_Land_CamShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJim_Land_CamShake_C>();
	}
};

}

