#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_Desert_Cactus_06

#include "Basic.hpp"

#include "Parent_Tree_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Prop_Desert_Cactus_06.Prop_Desert_Cactus_06_C
// 0x0000 (0x0CB0 - 0x0CB0)
class AProp_Desert_Cactus_06_C final : public AParent_Tree_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Prop_Desert_Cactus_06_C">();
	}
	static class AProp_Desert_Cactus_06_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_Desert_Cactus_06_C>();
	}
};

}

