#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ScoreBadgeProviderMission

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass ScoreBadgeProviderMission.ScoreBadgeProviderMission_C
// 0x0000 (0x0028 - 0x0028)
class IScoreBadgeProviderMission_C final : public IInterface
{
public:
	void GetScoreBadgeInfos(EStatCategory ScoreCategory, TArray<struct FCollectionMissionBadgeDisplayInfo>* BadgeInfos);
	void GetTotalScore(EStatCategory ScoreCategory, int32* Score);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ScoreBadgeProviderMission_C">();
	}
	static class IScoreBadgeProviderMission_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IScoreBadgeProviderMission_C>();
	}
};

}

