#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SkillTreeGroupBGMinusH

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SkillTreeGroupBG-H.SkillTreeGroupBG-H_C
// 0x0000 (0x04F0 - 0x04F0)
class USkillTreeGroupBGMinusH_C : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SkillTreeGroupBG-H_C">();
	}
	static class USkillTreeGroupBGMinusH_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkillTreeGroupBGMinusH_C>();
	}
};

}

