#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SkillTreeGroupBGMinusHMinusWide

#include "Basic.hpp"

#include "SkillTreeGroupBGMinusH_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SkillTreeGroupBG-H-Wide.SkillTreeGroupBG-H-Wide_C
// 0x0000 (0x04F0 - 0x04F0)
class USkillTreeGroupBGMinusHMinusWide_C final : public USkillTreeGroupBGMinusH_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SkillTreeGroupBG-H-Wide_C">();
	}
	static class USkillTreeGroupBGMinusHMinusWide_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkillTreeGroupBGMinusHMinusWide_C>();
	}
};

}

