#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusBaseMinusSMinusBMinusSMinus70pc

#include "Basic.hpp"

#include "TextStyleMinusBaseMinusSMinusB_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Base-S-B-S-70pc.TextStyle-Base-S-B-S-70pc_C
// 0x0000 (0x00C0 - 0x00C0)
class UTextStyleMinusBaseMinusSMinusBMinusSMinus70pc_C final : public UTextStyleMinusBaseMinusSMinusB_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Base-S-B-S-70pc_C">();
	}
	static class UTextStyleMinusBaseMinusSMinusBMinusSMinus70pc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusBaseMinusSMinusBMinusSMinus70pc_C>();
	}
};

}

