#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusBaseMinusXXSMinusBMinusOutline

#include "Basic.hpp"

#include "TextStyleMinusBaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Base-XXS-B-Outline.TextStyle-Base-XXS-B-Outline_C
// 0x0000 (0x00C0 - 0x00C0)
class UTextStyleMinusBaseMinusXXSMinusBMinusOutline_C final : public UTextStyleMinusBaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Base-XXS-B-Outline_C">();
	}
	static class UTextStyleMinusBaseMinusXXSMinusBMinusOutline_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusBaseMinusXXSMinusBMinusOutline_C>();
	}
};

}

