#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusHeaderMinusXS

#include "Basic.hpp"

#include "TextStyleMinusHeaderParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Header-XS.TextStyle-Header-XS_C
// 0x0000 (0x00C0 - 0x00C0)
class UTextStyleMinusHeaderMinusXS_C final : public UTextStyleMinusHeaderParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Header-XS_C">();
	}
	static class UTextStyleMinusHeaderMinusXS_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusHeaderMinusXS_C>();
	}
};

}

