#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusBaseMinusLMinusS

#include "Basic.hpp"

#include "TextStyleMinusBaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Base-L-S.TextStyle-Base-L-S_C
// 0x0000 (0x00C0 - 0x00C0)
class UTextStyleMinusBaseMinusLMinusS_C final : public UTextStyleMinusBaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Base-L-S_C">();
	}
	static class UTextStyleMinusBaseMinusLMinusS_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusBaseMinusLMinusS_C>();
	}
};

}

