#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusBaseMinusXSMinusHUDMinusShieldBarMax

#include "Basic.hpp"

#include "TextStyleMinusBaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Base-XS-HUD-ShieldBarMax.TextStyle-Base-XS-HUD-ShieldBarMax_C
// 0x0000 (0x00C0 - 0x00C0)
class UTextStyleMinusBaseMinusXSMinusHUDMinusShieldBarMax_C final : public UTextStyleMinusBaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Base-XS-HUD-ShieldBarMax_C">();
	}
	static class UTextStyleMinusBaseMinusXSMinusHUDMinusShieldBarMax_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusBaseMinusXSMinusHUDMinusShieldBarMax_C>();
	}
};

}

