#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusBaseMinusSMinusS_LightGray

#include "Basic.hpp"

#include "TextStyleMinusBaseMinusS_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Base-S-S_LightGray.TextStyle-Base-S-S_LightGray_C
// 0x0000 (0x00C0 - 0x00C0)
class UTextStyleMinusBaseMinusSMinusS_LightGray_C final : public UTextStyleMinusBaseMinusS_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Base-S-S_LightGray_C">();
	}
	static class UTextStyleMinusBaseMinusSMinusS_LightGray_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusBaseMinusSMinusS_LightGray_C>();
	}
};

}

