#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusScorePopup

#include "Basic.hpp"

#include "TextStyleMinusScorePlacementGold_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-ScorePopup.TextStyle-ScorePopup_C
// 0x0000 (0x00C0 - 0x00C0)
class UTextStyleMinusScorePopup_C : public UTextStyleMinusScorePlacementGold_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-ScorePopup_C">();
	}
	static class UTextStyleMinusScorePopup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusScorePopup_C>();
	}
};

}

