#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusScorePlacementBronze

#include "Basic.hpp"

#include "TextStyleMinusScorePlacementGold_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-ScorePlacementBronze.TextStyle-ScorePlacementBronze_C
// 0x0000 (0x00C0 - 0x00C0)
class UTextStyleMinusScorePlacementBronze_C final : public UTextStyleMinusScorePlacementGold_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-ScorePlacementBronze_C">();
	}
	static class UTextStyleMinusScorePlacementBronze_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusScorePlacementBronze_C>();
	}
};

}

