#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusBaseMinusXSMinusBMinusSMinusGreenMinusOutline

#include "Basic.hpp"

#include "TextStyleMinusBaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Base-XS-B-S-Green-Outline.TextStyle-Base-XS-B-S-Green-Outline_C
// 0x0000 (0x00C0 - 0x00C0)
class UTextStyleMinusBaseMinusXSMinusBMinusSMinusGreenMinusOutline_C final : public UTextStyleMinusBaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Base-XS-B-S-Green-Outline_C">();
	}
	static class UTextStyleMinusBaseMinusXSMinusBMinusSMinusGreenMinusOutline_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusBaseMinusXSMinusBMinusSMinusGreenMinusOutline_C>();
	}
};

}

