#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusScorePlacementGold

#include "Basic.hpp"

#include "TextStyleMinusHeaderMinusL_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-ScorePlacementGold.TextStyle-ScorePlacementGold_C
// 0x0000 (0x00C0 - 0x00C0)
class UTextStyleMinusScorePlacementGold_C : public UTextStyleMinusHeaderMinusL_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-ScorePlacementGold_C">();
	}
	static class UTextStyleMinusScorePlacementGold_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusScorePlacementGold_C>();
	}
};

}

