#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TooltipMinusDescriptionText

#include "Basic.hpp"


namespace SDK::Params
{

// Function Tooltip-DescriptionText.Tooltip-DescriptionText_C.ExecuteUbergraph_Tooltip-DescriptionText
// 0x0004 (0x0004 - 0x0000)
struct TooltipMinusDescriptionText_C_ExecuteUbergraph_TooltipMinusDescriptionText final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

