#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: XpReasonFeedItem

#include "Basic.hpp"


namespace SDK::Params
{

// Function XpReasonFeedItem.XpReasonFeedItem_C.PlayPresentEffect
// 0x0004 (0x0004 - 0x0000)
struct XpReasonFeedItem_C_PlayPresentEffect final
{
public:
	float                                         PlaybackSpeed;                                     // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function XpReasonFeedItem.XpReasonFeedItem_C.SetXpText
// 0x0018 (0x0018 - 0x0000)
struct XpReasonFeedItem_C_SetXpText final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};

}

